name: LovelyGourmet
favicon: null
layout_spectrum: 0.3086929451674223
typography_spectrum: 0.6490508471615613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.41767915477976203
  lightness: 0.9279281608760357
  saturation: 0.4670792657416314
  rhythmicContrast: 0.5550352798309177
purpose: []
